version: 2.1

orbs:
  greenzie: greenzie/build_and_publish_debs@0.2.0

parameters:
  manual_deploy:
    description: "Trigger a manual amd64 deploy to greenzie-experimental"
    type: boolean
    default: false

workflows:
  version: 2
  pushbuild:
    when:
      not: << pipeline.parameters.manual_deploy >>
    jobs:
      # Build jobs
      - greenzie/debian_build:
          name: "amd_debian_build"
          context: GREENZIE
          platform: amd64
          executor: greenzie/debianize_amd64

  manualdeploy:
    when: << pipeline.parameters.manual_deploy >>
    jobs:
      - greenzie/debian_build:
          name: "amd_debian_build"
          context: GREENZIE
          platform: amd64
          executor: greenzie/debianize_amd64

      - greenzie/debian_deploy_experimental_ssh:
          name: "deploy_amd64_greenzie"
          context: GREENZIE
          requires:
            - amd_debian_build
